core/issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('auth/', include('accounts.urls'))
]

core/tracker/urls.py
from django.urls import path

from tracker.views.add import AddView
from tracker.views.add_project import AddProjectView
from tracker.views.base import IndexView
from tracker.views.base_project import ProjectView
from tracker.views.delete import Delete
from tracker.views.delete_project import DeleteProjectView
from tracker.views.edit import EditView
from tracker.views.edit_project_view import EditProjectView
from tracker.views.edit_user_view import EditUserView
from tracker.views.project_view import ProjectDetailView
from tracker.views.task_view import TaskView

urlpatterns = [
    path('', IndexView.as_view(), name='main'),
    path('task/<int:pk>', TaskView.as_view(), name='task'),
    path('add/<int:pk>', AddView.as_view(), name='add'),
    path('edit/<int:pk>', EditView.as_view(), name='edit'),
    path('delete/confirm/<int:pk>', Delete.as_view(), name='delete'),
    path('projects/', ProjectView.as_view(), name='projects'),
    path('project/<int:pk>', ProjectDetailView.as_view(), name='project'),
    path('add/project', AddProjectView.as_view(), name='add_project'),
    path('edit/user/<int:pk>', EditUserView.as_view(), name='edit_user'),
    path('delete/project/<int:pk>', DeleteProjectView.as_view(), name='delete_project'),
    path('edit/project/<int:pk>', EditProjectView.as_view(), name='edit_project')
]

core/tracker/models/issue_tracker.py
from django.db import models
from django.utils import timezone


class IssueTracker(models.Model):
    summary = models.CharField(verbose_name='Заголовок', max_length=200, null=False, blank=False)
    description = models.TextField(verbose_name='Подробное описание', max_length=500, null=True, blank=True)
    status = models.ForeignKey('tracker.Status', related_name='statuses', blank=True, on_delete=models.RESTRICT,
                               verbose_name='Статус', default='1')
    project = models.ForeignKey('tracker.Project', related_name='projects', blank=True, verbose_name='Проект',
                                on_delete=models.CASCADE, default='1')
    type = models.ManyToManyField('tracker.Type', related_name='types', blank=True, verbose_name='Тип', default='1')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    changed_at = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    is_deleted = models.BooleanField(verbose_name='Удалено', default=False, null=False)

    def delete(self, using=None, keep_parents=False):
        self.deleted_at = timezone.now()
        self.is_deleted = True
        self.save()

    def __str__(self):
        return f'{self.summary}'

core/tracker/models/project.py
from django.contrib.auth.models import User
from django.db import models


class Project(models.Model):
    name = models.CharField(verbose_name='Название', max_length=200, null=False, blank=False)
    start_date = models.DateField(verbose_name='Дата начала', null=True, blank=True)
    end_date = models.DateField(verbose_name='Дата окончания', null=True, blank=True)
    description = models.TextField(verbose_name='Описание', max_length=200, null=True, blank=True)
    users = models.ManyToManyField(User, related_name='users', blank=True, verbose_name='Пользователь', default='1')

    def __str__(self):
        return f'{self.name}'

core/tracker/views/add_project.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView
from django.urls import reverse_lazy

from tracker.forms import AddProjectForm
from tracker.models import Project
from tracker.views import CustomUserPassesMixin


class AddProjectView(CustomUserPassesMixin, LoginRequiredMixin, CreateView):
    template_name = 'add_project.html'
    # success_url = reverse_lazy('projects')
    model = Project
    form_class = AddProjectForm
    groups = ['manager', 'root']

    def get_success_url(self):
        set_user = get_object_or_404(Project, pk=self.object.pk)
        set_user.users.add(self.request.user)
        set_user.save()
        return reverse_lazy('projects')

core/tracker/views/base.py
from urllib.parse import urlencode

from django.shortcuts import render
from django.views.generic import ListView

from tracker.forms import SearchForm
from tracker.models.issue_tracker import IssueTracker
from django.db.models import Q


class IndexView(ListView):
    template_name = 'main_page.html'
    model = IssueTracker
    context_object_name = 'articles'
    paginate_by = 10
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset.filter(is_deleted=False)

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

core/tracker/views/edit_project_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView
from django.urls import reverse_lazy

from tracker.forms import AddProjectForm
from tracker.models import Project
from tracker.views import CustomUserPassesMixin


class EditProjectView(CustomUserPassesMixin, LoginRequiredMixin, UpdateView):
    template_name = "edit_project.html"
    form_class = AddProjectForm
    model = Project
    success_url = reverse_lazy('projects')
    groups = ['manager', 'root']

core/tracker/views/edit_user_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from tracker.forms import EditForm
from tracker.models import Project
from tracker.views import CustomUserPassesMixin


class EditUserView(CustomUserPassesMixin, LoginRequiredMixin, UpdateView):
    template_name = "edit_user.html"
    form_class = EditForm
    model = Project
    success_url = reverse_lazy('projects')
    context_object_name = 'project'
    groups = ['lead', 'manager', 'root']

core/tracker/views/project_view.py
from django.views.generic import DetailView

from tracker.models import Project
from tracker.models.issue_tracker import IssueTracker


class ProjectDetailView(DetailView):
    template_name = 'project_view.html'
    model = Project
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        task = IssueTracker.objects.filter(project=self.kwargs['pk'])
        context['tasks'] = task.filter(is_deleted=False)
        return context

core/tracker/views/task_view.py
from django.views.generic import DetailView

from tracker.models.issue_tracker import IssueTracker


class TaskView(DetailView):
    template_name = 'task_view.html'
    model = IssueTracker
    context_object_name = 'task'

core/templates/add_project.html
{% extends 'base.html' %}
{% block title %} Add {% endblock %}
{% block content %}
    <h4 class="text-center my-3 pb-3">Добавить проект</h4>
    <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2"
          action="{% url 'add_project' %}" method="POST">
        {% include 'partial/add_form.html' with button_text='Добавить' %}
    </form>
{% endblock %}

core/templates/add_task.html
{% extends 'base.html' %}
{% block title %} Add {% endblock %}
{% block content %}
    <h4 class="text-center my-3 pb-3">Добавить задачу</h4>
    <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2"
          action="" method="POST">
        {% include 'partial/add_edit_form.html' with button_text='Добавить' %}
    </form>
{% endblock %}

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}base{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
<section class="min-vh-100" style="background-color: #eee;">
    <div class="container py-5">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-9 col-xl-7">
                <div class="card rounded-3">
                    <div class="card-body p-4">
                        {% block content %} {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>

core/templates/edit_project.html
{% extends 'base.html' %}
{% block title %} Add {% endblock %}
{% block content %}
    <h4 class="text-center my-3 pb-3">Редактировать проект</h4>
    <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2"
          action="" method="POST">
        {% include 'partial/add_form.html' with button_text='Редактировать' %}
    </form>
{% endblock %}

core/templates/edit_task.html
{% extends 'base.html' %}
{% block title %} Edit task {% endblock %}

{% block content %}
    <h4 class="text-center my-3 pb-3">Редактировать Задачу</h4>
    <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2"
          action="{% url 'edit' article.pk %}" method="POST">
        {% include 'partial/add_edit_form.html' with button_text='Редактировать' %}
    </form>
{% endblock %}

core/templates/edit_user.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

    <form action="{% url 'edit_user' project.pk %}" class="col text-center" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Редактировать" %}
    </form>

{% endblock %}

core/templates/main_page.html
{% extends 'base.html' %}
{% block title %} Main {% endblock %}
{% block content %}
    <h4 class="text-center my-3 pb-3">Список Задач</h4>
    {% include 'partial/search.html' %}
    <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
        <div class="col-12 mt-4">
            <a href="{% url 'projects' %}" type="submit" class="btn btn-primary">Проекты</a>
            {% if user.is_authenticated %}


                <a href="{% url 'logout' %}" type="submit" class="btn btn-dark">Выход</a>
                <div class="text-center mt-4">
                <span class="">Привет, {{ user.username }}!</span>
                </div>


            {% else %}
                <a href="{% url 'login' %}" type="submit" class="btn btn-dark">Вход</a>
                <a href="{% url 'register' %}" type="submit" class="btn btn-dark">Регистрация</a>
            {% endif %}
        </div>
    </form>
    <table class="table mb-4">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Задачи</th>
            <th scope="col">Статус</th>
            <th scope="col">Тип</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <th scope="row">{{ article.pk }}</th>
                <td>{{ article.summary }}</td>
                <td>{{ article.status }}</td>
                <td>{% for type in article.type.all %}{{ type.name }} {% if not forloop.last %},
                {% endif %} {% endfor %}</td>
                <td><a href="{% url 'task' article.pk %}" class="btn btn-dark">Подробнее</a></td>
            </tr>
            {% empty %}
            <tr>
                <td>
                    Задачи не найдены
                </td>
            </tr>
        {% endfor %}
        </tbody>
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
    </table>

{% endblock %}

core/templates/project_page.html
{% extends 'base.html' %}
{% block title %} Projects {% endblock %}
{% block content %}
    <h4 class="text-center my-3 pb-3">Список проектов</h4>
    <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
        <div class="col-12">
            {% if user.is_authenticated %}
                {% if perms.tracker.add_project %}

                            <a href="{% url 'add_project' %}" type="submit" class="btn btn-primary">Добавить</a>

                {% endif %}
            {% endif %}

            <a href="{% url 'main' %}" type="submit" class="btn btn-primary">Задачи</a>
        </div>
    </form>
    <table class="table mb-4">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Проект</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for project in projects %}
            <tr>
                <th scope="row">{{ project.pk }}</th>
                <td>{{ project.name }}</td>
                <td><a href="{% url 'project' project.pk %}" class="btn btn-dark">Подробнее</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

core/templates/project_view.html
{% extends 'base.html' %}
{% block title %} Project {{ project.id }} {% endblock %}

{% block content %}
    <form method="post" action="{% url 'delete_project' project.pk %}">{% csrf_token %}
        <h4 class="text-center my-3 pb-3">{{ project.name }}</h4>
        <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
            <div class="col text-center">
                <a href="{% url 'projects' %}" type="submit" class="btn btn-primary">Проекты</a>
                {% if user.is_authenticated %}
                    {% if perms.tracker.add_issuetracker %}
                        {% for user in project.users.all %}
                            {% if user == request.user %}
                                <a href="{% url 'add' project.pk %}" type="submit" class="btn btn-primary">Добавить
                                    задачу</a>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    {% if perms.tracker.change_project %}

                        <a href="{% url 'edit_project' project.pk %}" type="submit" class="btn btn-primary">Редактировать</a>

                    {% endif %}
                    {% if perms.tracker.delete_project %}

                        <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                                data-bs-target="#exampleModal">
                            Удалить
                        </button>
                        <div class="modal fade" id="exampleModal" tabindex="-1"
                             aria-labelledby="exampleModalLabel"
                             aria-hidden="true" style="display: none;">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Вы уверены?</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                aria-label="Close"></button>
                                    </div>
                                    <div class="modal-footer">
                                        <div class="col-12">
                                            <a href="{% url 'main' %}" type="submit" class="btn btn-primary">Вернуться
                                                на
                                                главную</a>
                                            <input type="submit" class="btn btn-danger" value="Да">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endif %}
                {% endif %}
            </div>

        </form>
        <table class="table mb-4">
            <thead>
            <tr>
                <th scope="col">Проект</th>
                <th scope="col">Дата начала</th>
                <th scope="col">Дата окончания</th>
                <th scope="col">Полное описание</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ project.name }}</td>
                <td>{{ project.start_date }}</td>
                <td>{{ project.end_date }}</td>
                <td class="text-break">{{ task.description|linebreaks }}</td>
            </tr>
            </tbody>
        </table>
        <table class="table mb-4">
            <h4 class="text-center my-3 pb-3">Список Задач по проекту</h4>
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Задачи</th>
                <th scope="col">Статус</th>
                <th scope="col">Тип</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for task in tasks %}
                <tr>
                    <th scope="row">{{ task.pk }}</th>
                    <td>{{ task.summary }}</td>
                    <td>{{ task.status }}</td>
                    <td>{% for type in task.type.all %}{{ type.name }} {% if not forloop.last %},
                    {% endif %} {% endfor %}</td>
                    <td><a href="{% url 'task' task.pk %}" class="btn btn-dark">Подробнее</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% if user %}
            <table class="table mb-4">
                <h4 class="text-center my-3 pb-3">Список пользователей проекта</h4>
                <thead>
                <tr>
                    <th scope="col">Пользователи</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{% for user in project.users.all %}{{ user }} {% if not forloop.last %},
                    {% endif %}{% endfor %} </td>
                </tr>
                </tbody>
            </table>
        {% else %}
        {% endif %}
        {% if user.is_authenticated %}
            {% if perms.tracker.change_project %}
                {% for user in project.users.all %}
                    {% if user == request.user %}
                        <a href="{% url 'edit_user' project.pk %}" type="submit" class="btn btn-primary text-center">Редактировать
                            пользователей</a>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endif %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
                crossorigin="anonymous"></script>
    </form>
{% endblock %}

core/templates/task_view.html
{% extends 'base.html' %}
{% block title %} Task {{ task.id }} {% endblock %}

{% block content %}
    <form method="post" action="{% url 'delete' task.id %}">{% csrf_token %}
        <h4 class="text-center my-3 pb-3">{{ task.description }}</h4>
        <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
            <div class="col text-center">
                <a href="{% url 'main' %}" type="submit" class="btn btn-primary">Главная страница</a>
                {% if user.is_authenticated %}
                    {% if perms.tracker.change_issuetracker %}
                        {% for user in task.project.users.all %}
                            {% if user == request.user %}
                                <a href="{% url 'edit' task.id %}" type="submit"
                                   class="btn btn-warning">Редактировать</a>
                            {% endif %}
                        {% endfor %}

                    {% endif %}
                    {% if perms.tracker.delete_issuetracker %}
                        {% for user in task.project.users.all %}
                            {% if user == request.user %}
                                <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                                        data-bs-target="#exampleModal">
                                    Удалить
                                </button>
                                <div class="modal fade" id="exampleModal" tabindex="-1"
                                     aria-labelledby="exampleModalLabel"
                                     aria-hidden="true" style="display: none;">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Вы уверены?</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                            </div>
                                            <div class="modal-footer">
                                                <div class="col-12">
                                                    <a href="{% url 'main' %}" type="submit" class="btn btn-primary">Вернуться
                                                        на
                                                        главную</a>
                                                    <input type="submit" class="btn btn-danger" value="Да">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endif %}

            </div>

        </form>
        <table class="table mb-4">
            <thead>
            <tr>
                <th scope="col">Задача</th>
                <th scope="col">Статус</th>
                <th scope="col">Тип</th>
                <th scope="col">Полное описание</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ task.summary }}</td>
                <td>{{ task.status }}</td>
                <td>{% for type in task.type.all %}{{ type.name }} {% if not forloop.last %},
                {% endif %} {% endfor %}</td>
                <td class="text-break">{{ task.description|linebreaks }}</td>
            </tr>
            </tbody>
        </table>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
                crossorigin="anonymous"></script>
    </form>
{% endblock %}